### ISSUE TITLE
显示进度建议

### ISSUE THREAD

**Issue by VainAnts** [NewHuLe/AppUpdate#1]
通知中心更新下载进度更好，建议提供选项，强制更新应用才在应用内更新，应用体验更健康

**Comment by NewHuLe** [comment]
感谢你的建议，已经更改下载通知栏的配置，目前测试oppo部分机型会在下载的时候通知栏显示：1个任务正在下载，其他机型则会显示有下载进度条，请更新到v1.2版本。
