### ISSUE TITLE
无法自定义弹框布局

### ISSUE THREAD

**Issue by chenxiaofei910714** [NewHuLe/AppUpdate#10]
无法灵活自定义布局，UpdateRemindDialog在UpdateManager中直接实例化了，而UpdateRemindDialog中有判断必须是     
// 默认布局的显示
        if (appUpdate.getUpdateResourceId() == R.layout.dialog_update) {
创建XML文件，也只是取消控件和更新能够被初始化，不能灵活完全接管自己想创建的布局

**Comment by NewHuLe** [comment]
@chenxiaofei910714 建议你在静默下载的模式下使用自定义布局（取消更新的id要定义为btnUpdateLater，立即更新的id要定义为btnUpdateNow）；由于非静默模式下自从v1.3版本后将单独的更新进度框与下载失败框融合进了更新提醒框，里面包含的控件较多，导致自定义不够灵活（目前只能通过appupdate参数自定义一些显示），无法直接传入一个单独的XML，后期有考虑优化，感谢你的建议....

**Comment by chenxiaofei910714** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"NewHuLe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 下午3:28
收件人:&nbsp;"NewHuLe/AppUpdate"<AppUpdate@noreply.github.com&gt;;
抄送:&nbsp;"陈晓飞"<chenxiao03@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NewHuLe/AppUpdate] 无法自定义弹框布局 (#10)




暂时下载你的demo，本地依赖自己改动布局了，里面触发按钮事件太多了、太多隐藏和显示，不够优雅也不好维护，我唯发送一担心的是downloadmager下载兼容性会不会不太好，我第一次用这个玩意，公司的测试机都基本都试了没问题，就是没有三星手机可以星

**Comment by NewHuLe** [comment]
@chenxiaofei910714 是的，你可下载一份源码，需要的话可以自己改造一下。非静默下载模式下当初有考虑，如果完全自定义布局，需要自己代码监听的事件就太多（比如下载进度，弹框消失、权限），处理起来会更麻烦，so非静默模式目前只能简单的自定义，三星手机没问题我这边都测试过，至于兼容性问题不大，库里面有做防护，有问题可以反馈。

**Comment by chenxiaofei910714** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"NewHuLe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 下午3:55
收件人:&nbsp;"NewHuLe/AppUpdate"<AppUpdate@noreply.github.com&gt;;
抄送:&nbsp;"陈晓飞"<chenxiao03@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NewHuLe/AppUpdate] 无法自定义弹框布局 (#10)

知道为什么进度条不显示值？直接下载完了
