### ISSUE TITLE
下载文件的总长度出现负数

### ISSUE THREAD

**Issue by chenxiaofei910714** [NewHuLe/AppUpdate#11]
long totalSize = cursor.getInt(cursor.getColumnIndex(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));这个会出现负数，作者demo里面不会，我本地移植到自己项目里就出现totalSize 很多次都是负数，只有最后两次才为正数，结果导致进度条只有下载完时直接显示到100

**Comment by NewHuLe** [comment]
@chenxiaofei910714 按照demo改的时候需要注意，我想这个问题应该是你进度计算使用了int类型造成的。

**Comment by chenxiaofei910714** [comment]
int status = cursor.getInt(cursor.getColumnIndex(DownloadManager.COLUMN_STATUS));
                long totalSize = cursor.getInt(cursor.getColumnIndex(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));
                long currentSize = cursor.getInt(cursor.getColumnIndex(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR));
                // 当前进度
                int mProgress;
                if (totalSize != 0) {
                    mProgress = (int) ((currentSize * 100) / totalSize);
                } else {
                    mProgress = 0;
                }
你的demo我只改了布局，其他都没有动，你原来也是计算的时候也是int型，我在想是不是项目里设置的NDK的CPU架构有关系
