### ISSUE TITLE
非静默下载，更新下载达到100%未自动弹出安装界面，停止不动。

### ISSUE THREAD

**Issue by supercodeing** [NewHuLe/AppUpdate#12]
如题，另外，本次下载达到100%下次启动再次立即更新依然还要重新下载，按理说此时已经下载过了，demo是下载完成后下次不会再下载而是直接用上次下载完成的apk安装。为啥接到我的项目里就不好使
所有机型都是

**Comment by supercodeing** [comment]
补充，研究一下发现8.0系统各个厂商处理安装未知应用权限可能不太一样。而且，这个权限并不是运行时权限，楼主运行时动态申请没有意义。而且据说canRequestPackageInstalls方法并不准确，有的永远返回false。所以只能下载以资源库方式引入楼主的这个项目，期待后续楼主更新再远程引入。

**Comment by NewHuLe** [comment]
关于canRequestPackageInstalls一直返回false的情况下，官方源码中有说明，因为处理的是Android O未知来源应用，所以targetSdkVersion必须要设置26以上，应该没什么问题了。

**Comment by NewHuLe** [comment]
关于canRequestPackageInstalls一直返回false的情况下，官方源码中有说明，因为处理的是Android O未知来源应用，所以targetSdkVersion必须要设置26以上，应该没什么问题了，而且事实上targetSdkVersion不是越低越好，开发的实际过程中尽可能调高一点来适配高版本。
至于为什么要动态申请安装未知应用是因为在Android O刚出来的那段时间，不申请部分手机是没法安装的，就算在清单文件中注册了也是没用的，有些手机无法弹出安装未知应用，亲自试过。

**Comment by NewHuLe** [comment]
另外，你说的下载成功后，下次还需要继续下载，这个问题有确认过原因嘛，或者有什么日志吗，我这边无法复现

**Comment by supercodeing** [comment]
> 关于canRequestPackageInstalls一直返回false的情况下，官方源码中有说明，因为处理的是Android O未知来源应用，所以targetSdkVersion必须要设置26以上，应该没什么问题了，而且事实上targetSdkVersion不是越低越好，开发的实际过程中尽可能调高一点来适配高版本。
> 至于为什么要动态申请安装未知应用是因为在Android O刚出来的那段时间，不申请部分手机是没法安装的，就算在清单文件中注册了也是没用的，有些手机无法弹出安装未知应用，亲自试过。

感谢楼主回复，上述反应的问题主要原因还是设备没有示开启未知应用安装权限，但是楼主源码动态申请权限的代码并没有跳到设置页面，而是走到权限申请那里没有任何反应了，所以代码和ui到此结束了。
我现在的做法是检查安装未知应用权限是否有，没有直接打开未知权限设置页面。用户手动打开后接着走楼主源码。
测试机两个都是8.0及以上系统，我们目前app targetsdk29。所以应该产生这个问题跟targetsdk是不是大于26关系不大了。
以上信息供楼主参考。

**Comment by NewHuLe** [comment]
不好意思哈，最近比较忙....
我这边实在无法复现你说的问题，更新库中是有打开未知来源设置界面的，具体如下：
![image](https://user-images.githubusercontent.com/6002150/84452845-89c35b80-ac89-11ea-9759-de99837cf910.png)
你那边能不能提供一下具体机型、版本和log信息我这边排查一下

**Comment by DevYJQ** [comment]
> > 关于canRequestPackageInstalls一直返回false的情况下，官方源码中有说明，因为处理的是Android O未知来源应用，所以targetSdkVersion必须要设置26以上，应该没什么问题了，而且事实上targetSdkVersion不是越低越好，开发的实际过程中尽可能调高一点来适配高版本。
> > 至于为什么要动态申请安装未知应用是因为在Android O刚出来的那段时间，不申请部分手机是没法安装的，就算在清单文件中注册了也是没用的，有些手机无法弹出安装未知应用，亲自试过。
> 
> 感谢楼主回复，上述反应的问题主要原因还是设备没有示开启未知应用安装权限，但是楼主源码动态申请权限的代码并没有跳到设置页面，而是走到权限申请那里没有任何反应了，所以代码和ui到此结束了。
> 我现在的做法是检查安装未知应用权限是否有，没有直接打开未知权限设置页面。用户手动打开后接着走楼主源码。
> 测试机两个都是8.0及以上系统，我们目前app targetsdk29。所以应该产生这个问题跟targetsdk是不是大于26关系不大了。
> 以上信息供楼主参考。

您好，项目中在用这个库吗？我测试发现有些问题，可以交流下吗？
