### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by KotlinLan** [NewHuLe/AppUpdate#3]
建议点击下载后，没必要再弹出一个dialog来专门显示进度条，可以用原来显示版本更新内容那个dialog来显示。

**Comment by NewHuLe** [comment]
@KotlinLan 建议挺好的，之前也有考虑过，下个版本有考虑优化

**Comment by KotlinLan** [comment]
@NewHuLe 打扰一下，怎么判断文件有没有下载过，现在想实现这样的需求：用户下载了，并且自动跳转到了安装页面，但是用户这个时候没有安装，下一次进来的又要重新下载，希望下一次进来的时候，立即更新就变成立即安装。请问可以把这个也优化进去吗，谢谢

**Comment by NewHuLe** [comment]
一种方案是每次打开app，都会去检测是否有新版本，此时拿服务器返回apk文件的md5值，与存储在本地文件apk的md5值做对比，一致的话，说明是同一个apk文件，不用下载，直接弹出安装

**Comment by NewHuLe** [comment]
根据你的建议，v1.3版本已经开启，参考v1.3版本

**Comment by KotlinLan** [comment]
@NewHuLe 好的，谢谢！
