### ISSUE TITLE
正在下载时按home键，下载进度异常

### ISSUE THREAD

**Issue by Ctergz** [NewHuLe/AppUpdate#5]
D/com.open.hule.library.downloadmanager.DownloadObserver: 75
 D/com.open.hule.library.downloadmanager.DownloadObserver: STATUS_RUNNING
 D/com.open.hule.library.downloadmanager.DownloadObserver: -74
 D/com.open.hule.library.downloadmanager.DownloadObserver: STATUS_RUNNING
 D/com.open.hule.library.downloadmanager.DownloadObserver: -70

**Comment by NewHuLe** [comment]
@Ctergz 感谢你的反馈，已经优化，请更新使用v1.4版本
