### ISSUE TITLE
开始下载后按home键，下载完成后dialog不消失

### ISSUE THREAD

**Issue by Ctergz** [NewHuLe/AppUpdate#6]
非强制更新，下载完成后在安装页面点击取消不安装，再打开app，dialog不消失
 W/System.err: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 W/System.err:     at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
 W/System.err:     at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
 W/System.err:     at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
 W/System.err:     at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
 W/System.err:     at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:250)
 W/System.err:     at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
 W/System.err:     at com.open.hule.library.view.BaseDialog.dismiss(BaseDialog.java:99)
 W/System.err:     at com.open.hule.library.utils.UpdateManager.dismissDialog(UpdateManager.java:194)
 W/System.err:     at com.open.hule.library.downloadmanager.DownloadHandler$1.run(DownloadHandler.java:51)
 W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
 W/System.err:     at android.os.Looper.loop(Looper.java:148)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by NewHuLe** [comment]
@Ctergz 感谢你的反馈，已经优化，请更新使用v1.4版本
