### ISSUE TITLE
部分机型无法更新

### ISSUE THREAD

**Issue by FeverCombo3** [NewHuLe/AppUpdate#7]
我用的也是Downloadmanager更新，但是收到反馈某些机型下载没进度，有个测试机是Nexus 6p更新不了，我看了一下发现Downloadmanager 的下载状态一直是PENDING,下了你的demo测试发现也是下不了，进度一直是0，发现原因是cursor.moveToNext()返回的false导致无法更新状态，这是不是Downloadmanager内部的bug？

**Comment by NewHuLe** [comment]
@FeverCombo3 已经修复，请更新到v1.5版本，这是因为系统默认的下载是通过计量网络连接造成的，可以说是个系统bug，但是我们也可以自己控制。
