### ISSUE TITLE
安装一直提示着

### ISSUE THREAD

**Issue by moselon** [NewHuLe/AppUpdate#9]
![image](https://user-images.githubusercontent.com/8391289/71496852-6437c680-2890-11ea-84dc-572fe3dad9bf.png)
![image](https://user-images.githubusercontent.com/8391289/71496867-7285e280-2890-11ea-87eb-cd2789d37c25.png)

**Comment by NewHuLe** [comment]
@moselon 这是属于你自己手机装了debug包，然后下载安装的是release包，造成安装冲突问题

**Comment by moselon** [comment]
![image](https://user-images.githubusercontent.com/8391289/71509972-34a4b080-28c8-11ea-988f-fab48f75756d.png)
savaPath是必填吗，我没有写，下载后启动安装闪退了

**Comment by NewHuLe** [comment]
@moselon 除了url地址其他都是非必填。
提问请参考[提问须知](https://github.com/NewHuLe/AppUpdate/issues/8)，尽量提供手机版本、问题与日志，方便排查是不是库的问题，
